### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by kesior** [dternyak/monerochain#5]
Hello! I just updated my npm and nodejs to the newest version available in apt-get. Upon trying to run the npm run dev, I get the following:

`xxxx@boss:~/monerochain$ npm run dev

> MoneroChain@0.0.1 dev /home/xxxx/monerochain
> node webpack_config/server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/xxxxx/monerochain/webpack_config/server.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! MoneroChain@0.0.1 dev: `node webpack_config/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MoneroChain@0.0.1 dev script 'node webpack_config/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the MoneroChain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node webpack_config/server.js
`

**Comment by dternyak** [comment]
Thanks for the heads up. I haven't been maintaining this repo very well, as I'm working on a monerochain 2.0 when I happen to have some very spare time.

The functionality is essentially the same, but with a significantly cleaner webpack setup and cleaner code overall.

I'll try to get this up in a repo just in case others want to contribute, but in the meantime this repo won't be getting a lot of love.

**Comment by kesior** [comment]
Alright, fair enough. I guess I'll keep watching for releases as this explorer is simple yet looks nice :)
